"""
Constantes compartilhadas para players.
Substitui magic numbers por constantes nomeadas.
"""

# Probabilidades de blefe padrão
BLUFF_PROBABILITY_TIGHT = 0.08
BLUFF_PROBABILITY_AGGRESSIVE = 0.35
BLUFF_PROBABILITY_RANDOM = 0.25
BLUFF_PROBABILITY_SMART = 0.15
BLUFF_PROBABILITY_BALANCED = 0.15
BLUFF_PROBABILITY_ADAPTIVE = 0.20
BLUFF_PROBABILITY_LEARNING = 0.20

# Thresholds de força de mão
HAND_STRENGTH_VERY_STRONG = 70
HAND_STRENGTH_STRONG = 50
HAND_STRENGTH_MEDIUM = 25
HAND_STRENGTH_WEAK = 10

# Thresholds de tightness
TIGHTNESS_THRESHOLD_DEFAULT = 25
TIGHTNESS_THRESHOLD_CONSERVATIVE = 30
TIGHTNESS_THRESHOLD_AGGRESSIVE = 20

# Níveis de agressão
AGGRESSION_LEVEL_LOW = 0.3
AGGRESSION_LEVEL_MEDIUM = 0.5
AGGRESSION_LEVEL_HIGH = 0.7
AGGRESSION_LEVEL_VERY_HIGH = 0.85

# Valores de stack
STACK_INITIAL = 100
STACK_LOW_THRESHOLD = 0.7  # 70% do stack inicial
STACK_HIGH_THRESHOLD = 1.2  # 120% do stack inicial

# Tamanhos de pot
POT_SIZE_SMALL = 50
POT_SIZE_MEDIUM = 100
POT_SIZE_LARGE = 150

# Taxas de aprendizado
LEARNING_RATE_DEFAULT = 0.1
LEARNING_RATE_CONSERVATIVE = 0.05
LEARNING_RATE_AGGRESSIVE = 0.15

# Histórico de rodadas (quantas manter)
HISTORY_SIZE_SHORT = 10
HISTORY_SIZE_MEDIUM = 20
HISTORY_SIZE_LONG = 50

# Cartas altas
HIGH_CARDS = ['A', 'K', 'Q', 'J']

