import json
import os
import sys

# Add root directory to path to allow imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from web.supabase_client import get_supabase_client

def upload_translations(file_path='translations.json'):
    try:
        client = get_supabase_client()
    except Exception as e:
        print(f"Skipping upload: {e}")
        return

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Arquivo {file_path} não encontrado.")
        return

    rows_to_upsert = []

    # Transforma o JSON aninhado em linhas para o banco
    # Espera formato: { "KEY": { "en": "Value", "pt-br": "Valor" } }
    for key, translations in data.items():
        for lang_code, content in translations.items():
            rows_to_upsert.append({
                "key": key,
                "lang_code": lang_code,
                "content": content
            })

    print(f"Preparando para enviar {len(rows_to_upsert)} traduções...")

    # Create table if not exists
    try:
        with client.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS localizations (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        key TEXT NOT NULL,
                        lang_code TEXT NOT NULL,
                        content TEXT NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                        CONSTRAINT uq_localizations_key_lang UNIQUE (key, lang_code)
                    );
                    CREATE INDEX IF NOT EXISTS idx_localizations_lang ON localizations(lang_code);
                """)
                conn.commit()
                print("Tabela localizations verificada/criada.")
    except Exception as e:
        print(f"Erro ao criar tabela: {e}")

    if client.upsert_translations(rows_to_upsert):
        print("Sucesso! Traduções atualizadas.")
    else:
        print("Falha ao atualizar traduções.")

if __name__ == "__main__":
    upload_translations()
