-- Cria a tabela de traduções
CREATE TABLE localizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    lang_code TEXT NOT NULL, -- ex: 'en', 'pt-br'
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Garante que não haja duplicatas de chave para o mesmo idioma
    CONSTRAINT uq_localizations_key_lang UNIQUE (key, lang_code)
);

-- Index para buscar todas as traduções de um idioma rapidamente
CREATE INDEX idx_localizations_lang ON localizations(lang_code);

-- (Opcional) Habilitar Row Level Security (RLS) para leitura pública
ALTER TABLE localizations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" 
ON localizations FOR SELECT 
USING (true);

-- Política de escrita apenas para service_role ou admin (ajuste conforme sua auth)
-- CREATE POLICY "Enable insert for service role only" ...
